lint:
	cd api-gateway && GOLANGCI_LINT_CACHE=/tmp/golangci-lint-cache GOCACHE=/tmp/go-build-cache golangci-lint run ./cmd/... ./internal/...
	cd user-service && GOLANGCI_LINT_CACHE=/tmp/golangci-lint-cache GOCACHE=/tmp/go-build-cache golangci-lint run ./cmd/... ./internal/... ./pkg/...
